### ISSUE TITLE
argh.decorators.arg documentation unclear

### ISSUE THREAD

**Issue by ewerybody** [neithere/argh#102]
Hello! I'm not able to figure this out:
In the [API Reference about @arg](http://argh.readthedocs.io/en/latest/reference.html?highlight=add_argument#argh.decorators.arg) you def like:
`def load(args):` and then have `args.format` available in the function.

That looks awesome but ... I cannot reproduce this. It always says:
`argh.exceptions.AssemblingError: load: argument path does not fit function signature: args`

I even tried to look up [how you test this](https://github.com/neithere/argh/blob/master/test/test_decorators.py): Turns out you don't have any args set up in the `func`s

And how do you get to `@arg`? is it:
`from argh.decorators import arg` ?
Is this the same:
`@argh.arg` ? like in the test?

**Comment by neithere** [comment]
Good point, thank you! This example dates back to the old syntax when we couldn't handle ordinary function signatures. I'll update the docs today.

**Comment by neithere** [comment]
In short:

1. The old (argparse-inspired) syntax `def load(args)` is discouraged (however, you can turn it on via `@expects_obj`);
2. The pythonic syntax `def load(foo='bar')` is recommended;
3. These tests only care about the function attributes set before the assembling phase;
4. You can use `arg` either way but `from argh import arg` is probably the best option for `@arg`-heavy declarations and `@argh.arg` is optimal for occasional usage.

**Comment by ewerybody** [comment]
Ahhh yea nice! Thank you very much for the explanation! :] :+1:
