### ISSUE TITLE
Decorated functions don't introspect through __wrapped__

### ISSUE THREAD

**Issue by brilee** [neithere/argh#111]
Consider the following snippet

```
import argh
import functools

def decorated(f):
    @functools.wraps(f)
    def wrapped(*args, **kwargs):
        print("Wrapping function call")
        return f(*args, **kwargs)
    return wrapped


def test1(a, b=1):
    print("Hello World!", a, b)

@decorated
def test2(a, b=1):
    print("Hello World!", a, b)

@decorated
@decorated
def test3(a, b=1):
    print("Hello World!", a, b)

parser = argh.ArghParser()
parser.add_commands([test1, test2, test3])
argh.dispatch(parser)
```

There are two unexpected behaviors here. All three functions should present the same help documentation - but `test2` and `test3` only present `*args` as their documentation. Also, `test2` and `test3` both reject the keyword argument `b`:

```shell
$ python3 testing.py test1 blah --b=2
Hello World! blah 2
$ python3 testing.py test2 blah --b=2
usage: testing.py [-h] {test1,test2,test3} ...
testing.py: error: unrecognized arguments: --b=2
```

I recognize that this would be a change in behavior, and that maybe there are some reasons that you wouldn't want to unwrap a decorated function to introspect arguments. I'd love to hear what those reasons are, because I can't seem to think of any.

**Comment by neithere** [comment]
Hi Brian,

This behaviour is pretty normal: `@wraps` replaces the original function with another one, copying the name and docstring. The signature is different. It's easy to fix though specifically for this decorator in Python 3.x (not sure about the `x` though):
```diff
diff --git a/argh/utils.py b/argh/utils.py
index 8650bb7..c960863 100644
--- a/argh/utils.py
+++ b/argh/utils.py
@@ -49,6 +49,8 @@ def get_arg_spec(function):
     arguments of instance methods (`self`) and static methods (usually `cls`
     or something like this).
     """
+    if hasattr(function, '__wrapped__'):
+        function = function.__wrapped__
     spec = compat.getargspec(function)
     if inspect.ismethod(function):
         spec = spec._replace(args=spec.args[1:])

```
I think I'll commit it with some tests when I have some spare time.

**Comment by brilee** [comment]
Thanks for the fix! I should note that your fix only unwraps one layer of decorator; maybe the fix can instead be:
```
-    if hasattr(function, '__wrapped__'):
+    while hasattr(function, '__wrapped__'):
        function = function.__wrapped__
```

**Comment by neithere** [comment]
Good idea, thanks!
