### ISSUE TITLE
positional arguments should not lead to removal of short form of keyword arguments

### ISSUE THREAD

**Issue by anntzer** [neithere/argh#115]
```
def main(arg, argoption="foo"):
    pass

import argh
argh.dispatch_command(main)
```

```
$ python foo.py -h
usage: foo.py [-h] [--argoption ARGOPTION] arg

positional arguments:
  arg                   -

optional arguments:
  -h, --help            show this help message and exit
  --argoption ARGOPTION
                        'foo'
```

Note that there is no real risk of confusion between the two arguments to main, so `argoption` could be available as `-a` too.

**Comment by neithere** [comment]
That's a valid concern. In other words, a named CLI argument's short form (`-a`) should be checked for uniqueness vs. other named CLI arguments only; non-named CLI args should be ignored.

(I'm using the clumsy wording "named CLI argument" to avoid confusion with named Python arguments; the help groups are called "positional arguments" and "optional arguments" but in fact the developer may want to make some required arguments named. This is not currently supported by Argh but I'd like to add that support.)

**Comment by neithere** [comment]
Will be released in v.0.29.
