### ISSUE TITLE
raising CommandError leaves returncode as 0

### ISSUE THREAD

**Issue by sanga** [neithere/argh#118]
It feels a bit weird as if you raise a CommandError then presumably the program hasn't succeeded in which case I'd expected returncode to be nonzero so that a script would know programmatically that something failed.

**Comment by ekimekim** [comment]
Came here to post this, but it looks like this has been inactive for 2 years? This is a serious bug, where scripts fail but report that they succeed.

If the concern is backwards compatability, I suggest deprecating `CommandError` with its broken behaviour, and replacing it with something equivalent (eg. `CommandFailed`) which allows the exit code to be set, with the default being 1.

A less drastic option would be to add the ability to set the exit code in a CommandError, but have it default to 0. This is a smaller change but leaves the default as being dangerous and broken, which is definitely not ideal.

**Comment by acetylen** [comment]
Just to make some noise for the benefit of #124, this is a pretty serious issue still, another two years later.

**Comment by neithere** [comment]
@ekimekim thanks for raising the issue and fixing it in yaargh. Would you mind if I port https://github.com/ekimekim/yaargh/pull/12 to Argh?

**Comment by ekimekim** [comment]
> Would you mind if I port https://github.com/ekimekim/yaargh/pull/12 to Argh?

That would be great!

> I'd really rather ask you to take care of integration of this behaviour into Argh as your expertise on this topic is clearly deeper than mine at this point.

To be honest I haven't really worked on this at all in a few years, but I'd love to help. I'll get started on an upstreamable version of https://github.com/ekimekim/yaargh/pull/12 and we'll see how it goes.
