### ISSUE TITLE
help for *args

### ISSUE THREAD

**Issue by anntzer** [neithere/argh#119]
Currently, help (from annotation) for `*args` is not displayed:
```
def main(arg: "help", *other_args: "more help"):
    pass

if __name__ == "__main__":
    import argh
    argh.dispatch_command(main)
```
```
$ python /tmp/foo.py -h
usage: foo.py [-h] arg [other_args [other_args ...]]

positional arguments:
  arg         help
  other_args  -

optional arguments:
  -h, --help  show this help message and exit
```

I think argparse should be able to handle help for such arguments just fine?

**Comment by neithere** [comment]
I have to admit that using annotations as a way to store help messages was a bad idea in the long run. This functionality is now deprecated in favour of #107.
