### ISSUE TITLE
Cannot change the PARSER_FORMATTER for dispatch_command

### ISSUE THREAD

**Issue by halloleo** [neithere/argh#121]
When dispatching my main function with `argh.dispatch_command`, I want to provide another PARSER_FORMATTER. I tried:

    import argh
    import argparse

    argh.PARSER_FORMATTER = argparse.RawTextHelpFormatter

    def myfunct(arg, param=None):
        pass # here my working code

    if __name__ == '__main__':
        argh.dispatch_command(myfunct)

But when called with `--help` the resulting program still prints default values. So it still seems to use Argh's `CustomFormatter` instead of argparse's `RawTextHelpFormatter`.

When I use `set_default_command` and instantiate the parser myself, it works:

    import argh
    import argparse

    argh.PARSER_FORMATTER = argparse.RawTextHelpFormatter

    def myfunct(arg, param=None):
        pass # here my working code

    if __name__ == '__main__':
        parser = argparse.ArgumentParser(
             formatter_class=argh.PARSER_FORMATTER)
        argh.set_default_command(parser, myfunct)
        argh.dispatch(parser)

 So the problem must relate to *internal visibility* of `PARSER_FORMATTER` in Argh. Somehow I cannot change `argh.PARSER_FORMATTER` for the Argh module itself...

ps: For the record, I talked about this issue [on StackOverflow][so-post], but I guess here is the better place...

[Argh]: http://argh.readthedocs.io/

[so-post]: http://stackoverflow.com/questions/43201297/how-to-change-the-parser-formatter-when-using-pythons-argh-library

**Comment by neithere** [comment]
The constant is documented as `argh.dispatching.PARSER_FORMATTER` and should be used as such. I wouldn't recommend monkey-patching external libraries though. Using `ArghParser(formatter_class=X)` should be enough.

**Comment by halloleo** [comment]
Thanks @neithere. Good to know. So the second approach with `argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)` is the way to go. 

(I was just hoping to get away with less boilerplate...)
