### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jacobsvante** [neithere/argh#124]
There's been some good changes to the code since 0.26.2 was released, like https://github.com/neithere/argh/commit/d60c3f8f792c62e265767a438aae3eb7452f34a7. What would you say @neithere about releasing 0.26.3?

**Comment by hugovk** [comment]
Here's a list of changes to master since 0.26.2:

https://github.com/neithere/argh/compare/v0.26.2...master

**Comment by cscutcher** [comment]
Been over a year now. @neithere, if you've got no time to look after the project any more that's totally understandable but just wondering whether to look elsewhere for an actively released fork. In any case thanks for all the hard work up to now.

**Comment by neithere** [comment]
Sorry for the delay, I'm afraid I really don't have time for my FOSS projects nowadays. Every PR must be properly reviewed and tested, also in the context of existing issues. Once a bunch of them has accumulated, they should be reviewed as a whole. It takes a lot of time. For a number of reasons it was not a problem before but nearly impossible (for me) right now.

I'm going to transfer one of my projects ([django-autoslug](https://github.com/neithere/django-autoslug)) to the @jazzband organization and see if it works. If it does, I'll ask them if they want `argh`, too, and hand it over. That would prevent further stagnation of the project that I love but just can't take care of.

Andy

**Comment by cscutcher** [comment]
@neithere no worries! totally understandable! I hadn't heard of jazzband, they seem supercool. If it turns out they don't think argh is viable for their stewardship, and no one else is keen, then I'd be happy to look after it.

**Comment by metaperl** [comment]
so @neithere do you think argh maintainership should be turned over to @cscutcher ?

**Comment by tankorsmash** [comment]
@neithere I love argh, would love to have someone willing, like @cscutcher to take over.

**Comment by polm** [comment]
Would be great to have a new maintainer for this :heart:

**Comment by maphew** [comment]
Anyone can start maintaining a fork, make noise here (so the community knows), let @neithere know, and then he can transfer when there's the requisite combination of time and attention in his world to make that happen.

**Comment by hugovk** [comment]
If it's any motivation, Tidelift is offering ~$50/month for maintaining this library:

* https://tidelift.com/lifter/search/pypi/argh

**Comment by neithere** [comment]
Hey guys, thank you for your patience!

I'm glad to say that I'm back. Still not much free time, but at least I'm now again working 1) 100% with Python (compared to ~1% for the last six years), and 2) in a very FOSS-friendly company.

I'm going to try gradually getting Argh back in shape soon. There are lots of stale issues and PRs, forks and even maintenance offers. There are also some thoughts of my own as I've been using the library all this time and would like to fix some limitations.

It will take time to clean up the mess and outline the new roadmap. The best thing a volunteer can do to speed this up is find and tag duplicate issues and check which PRs are still relevant. This way we could at least have the simplest and most annoying issues killed off ASAP and have a fresh release before venturing into anything more interesting and complicated like mapping type annotations to argparse.

**Comment by neithere** [comment]
I think this time I'm actually back :)

The roadmap as I see it right now:

- 0.27 — the last version to support Python 2.7 (I can't resist the pun). Will include most of the pending PRs, mostly bugfixes. Somewhere this month.
- 0.28 — drops support for Python ≤ 3.8. Includes some enhancements from current PRs. Probably in a few months.
- 0.29 — probably some bugfixes for which no PRs exist yet. No ETA, hopefully this summer. Will depend on whether people start contributing PRs to fix current issues.
- 0.30 — significantly breaks backward compatibility to introduce #107 (the design is not completely clear yet).
- 1.0 — everything added before is stabilised, LTS. No ETA, hopefully by EOY or 2024.

**Comment by neithere** [comment]
To whom it may concern: v.0.27 is finally out! It took a mere 6 years. :D

The preparation of v.0.28 is already in progress (PR #157).
