### ISSUE TITLE
Confusing license information

### ISSUE THREAD

**Issue by nlohmann** [neithere/argh#125]
The repository contains both the GPLv3 (COPYING) as well as the LGPL 3 (COPYING.LESSER) license text. Github seems to use COPYING to label the repo as GPLv3 project (see https://github.com/neithere/argh/blob/master/COPYING):

<img width="993" alt="license" src="https://user-images.githubusercontent.com/159488/32700392-c0084f68-c7c4-11e7-9d8b-616634d0efb9.png">

As the README states

> Argh is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

file COPYING should be removed from the repository to avoid confusion - both from users as well as from Github's license detection algorithm.

**Comment by hugovk** [comment]
https://github.com/neithere/argh/pull/126#issuecomment-344770524:

> Unfortunately with LPGL v3, you really need to include GPL v3 in a file as well, since LGPL v3 is an amendment to GPL v3.
> 
> Prior versions stood on their own though.

Should this issue be closed?

**Comment by nlohmann** [comment]
I'm OK with closing. It's a pity that licensee is confused by this.
