### ISSUE TITLE
argh.arg decorator does not properly handle action=count and choices 

### ISSUE THREAD

**Issue by nirizr** [neithere/argh#127]
Setting up the following argument:

`@argh.arg('-v', '--verbose', action='count', type=int, choices=range(4), default=0)`

I'm getting the following error:
`TypeError: main: cannot add arg -v/--verbose: __init__() got an unexpected keyword argument 'type'`

Desired behavior is to properly handle that case of action='count' together with `choices` to only allow counts in a predefined range.

**Comment by neithere** [comment]
I'm afraid the request is invalid. The `arg` decorator merely passes its arguments to argparse; its `_CountAction` is unfortunately barely documented but it does not support choices, nor does it support an explicitly passed type (it's always `int` anyway).

A possible solution:
```python
@argh.arg("-v", "--verbose", action="count")
def main(verbose=0):
    capped_verbosity = min(verbose, MAX_VERBOSITY)
    return f"verbosity: {capped_verbosity}"
```
