### ISSUE TITLE
First example in docs fails for me

### ISSUE THREAD

**Issue by smontanaro** [neithere/argh#135]
Using Python 3.6.7 and argh 0.26.2, the [first example here](https://readthedocs.org/projects/argh/):

> from argh import *
> 
> @dispatch_command
> @arg('name')
> def main(args):
>     return 'Hello ' + args.name

fails with `argh.exceptions.AssemblingError: main: argument name does not fit function signature: args`. Am I missing something extremely basic, or has the code outrun the documentation?

**Comment by neithere** [comment]
Hey, I don't think this looks like an example from the documentation :)

The examples in the docs are correct and should run fine.
