### ISSUE TITLE
override function signature with decorator

### ISSUE THREAD

**Issue by tekumara** [neithere/argh#142]
I'd like to be able to override what's declared in the function signature with the decorator.

Example:

```python
@argh.arg("--config", help="Section of the config file to use")
@argh.arg("ami", help="ami id")
@cli.cmd
def delete_image(config: Dict[str, Any], ami: str) -> None:
``` 

In the above `@cli.cmd` injects the `config` dict. The optional `--config` string argument allows specifying an overriding config or uses the default if no value is provided.

However, argh doesn't like this:
```
argh.exceptions.AssemblingError: delete_image: argument "config" declared as positional (in function signature) and optional (via decorator)
```

**Comment by neithere** [comment]
Hm, I'm not sure if this should be supported by Argh. Its primary goal is to take a Python function and expose it via CLI. Overriding the signature is something that does not align with that goal.

In this case however there's another problem: you cannot map a function argument without a default value ("Python positional") to a named CLI argument. I have came to a conclusion that this design decision introduces unnecessary limitations and should be changed.

**Comment by neithere** [comment]
Tracking the latter in #146.

The solution for your use case would be something like this if I understood it correctly:
```python
def delete_image(config_section_name str, ami: str) -> None:
    config = cli.get_config(config_section_name)
    _delete_image(config, ami: str)
```
The original example does not make sense to me. Why does a CLI command expect a dictionary?
