### ISSUE TITLE
Search for completion on RTD shows no results

### ISSUE THREAD

**Issue by mcstafford-git** [neithere/argh#147]
I was pleased to find that [there is completion](https://argh.readthedocs.io/en/latest/reference.html) after the initial disappointment in empty results from 
[searching for completion](https://argh.readthedocs.io/en/latest/search.html?q=completion).

Thanks for this project.

**Comment by neithere** [comment]
Glad you found the project useful! The search seems to work for me right now, so I hope the problem was somehow resolved on the RTD side.
