### ISSUE TITLE
use kwargs from different function?

### ISSUE THREAD

**Issue by proximous** [neithere/argh#151]
I have a wrapper function:
```
def wrapper(**kwargs):
   try:
      myfunc(**kwargs)
   except:
      pass
```
and my desired function:
```
def myfunc(a="1", b="2"):
   print(a)
   print(b)
```
I would like to do something like:
```
argh.dispatch_command(wrapper)
```
How would I tell argh to call wrapper() but get the kwargs from myfunc()? Is this possible?

**Comment by neithere** [comment]
I believe this can be resolved as described in #111. Please reopen if this doesn't help.
