### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [neithere/argh#152]
Could you please consider to use unittest.mock instead of mock, either exclusively or optionally?

**Comment by pgajdos** [comment]
E. g.:
https://build.opensuse.org/package/view_file/home:pgajdos:python/python-argh/python-argh-no_mock.patch

I can make a PR, if you want.

**Comment by TheChymera** [comment]
@neithere [promised to return at some point](https://github.com/neithere/argh/issues/124#issuecomment-820376819), but apparently not yet.

**Comment by pgajdos** [comment]
Patch is now here:
https://build.opensuse.org/package/view_file/home:pgajdos:python/python-argh/python-argh-no_mock.patch

**Comment by neithere** [comment]
Fixed in c453f28eb76e0e81512e35a6800488ff2d2518d7, will be released in the next version.
