### ISSUE TITLE
tox.ini file missing from sdist on PyPI

### ISSUE THREAD

**Issue by mtelka** [neithere/argh#155]
This is similar issue as #129.  The `tox.ini`  file is missing in the sdist at PyPI (see [argh-0.26.2.tar.gz](https://files.pythonhosted.org/packages/e3/75/1183b5d1663a66aebb2c184e0398724b624cecd4f4b679cb6e25de97ed15/argh-0.26.2.tar.gz)), but it is in the source tarball here at github (see [v0.26.2.tar.gz](https://github.com/neithere/argh/archive/refs/tags/v0.26.2.tar.gz)).  Please add the `tox.ini`  file to the sdist.

**Comment by neithere** [comment]
I believe this should be fixed in the latest release (0.27).

**Comment by mtelka** [comment]
Oops, we need `reqs-dev.txt` too.  Sorry, I forgot to mention it here.

**Comment by neithere** [comment]
@mtelka right, thanks, I forgot to add it because in my head the file was already non-existent, as it is in the branch for 0.28 :) 
Should be fixed in 0.27.2.
