### ISSUE TITLE
Remove Makefile

### ISSUE THREAD

**Issue by neithere** [neithere/argh#164]
It was added years ago for building Debian packages. Related files from that commit seem to have been lost by now. It's unclear whether the file still serves any purpose. 

Perhaps contact the people who packaged Argh for Debian last time. @mnencia, [this page](https://tracker.debian.org/pkg/python-argh) says it was you, do you have any suggestion? Thanks!

**Comment by mnencia** [comment]
Hi @neithere, it was not me but Hannu Valtonen (see d988ac200e912593ccebecab09a92e865c012e87). Indeed the Debian packaging process removes any `debian` directory in the upstream and does not use the Makefile. If you are not using it, you can remove it.

**Comment by neithere** [comment]
Got it, thank you!
