### ISSUE TITLE
Setting the argument name with `dest` is ignored

### ISSUE THREAD

**Issue by mathieulongtin** [neithere/argh#224]
### Summary
You used to be able to override the argument name with `dest`, but that doesn't work anymore.

This was useful to allow things like `--json` without overriding the `json` module, for example.

### To Reproduce
Python script:
```python
import argh

@argh.arg("-l", dest="list_files")
def somefunc(list_files=False):
  pass
```

Command line input/output:
```
$ my-script.py ...
argh.assembling.ArgumentNameMappingError: somefunc: argument -l does not fit function signature: -l/--list-files
```

### Expected behavior

The old behavior where if `dest` is supplied, it overrides any guesses as to the destination argument.

### Environment

 - OS: Ubuntu
 - Python version: 3.10
 - Argh version: 0.31.2

**Comment by neithere** [comment]
Thanks, confirming, scheduled the next bugfix release.

**Comment by neithere** [comment]
Related, not necessarily a replacement: #222.
