### ISSUE TITLE
Optionally permit unknown args

### ISSUE THREAD

**Issue by boosh** [neithere/argh#57]
Hi,

It'd be useful if there was a way of permitting unknown args. This can be done by conditionally calling `args, unknown = parser.parse_known_args(argv, namespace=namespace)` instead of always calling `parser.parse_args()`.

Also see: https://stackoverflow.com/questions/12818146/python-argparse-ignore-unrecognised-arguments

Thanks

**Comment by georgexsh** [comment]
come from [a StackOverflow post](https://stackoverflow.com/questions/46883778/how-can-i-collect-unspecified-command-line-options-when-using-pythons-argh/46912858#46912858), from the unit test of this revision, when an unknown args passed, help message will be printed, is this a expected behavior?
