### ISSUE TITLE
Example to pass in STDIN to a command

### ISSUE THREAD

**Issue by hekaldama** [neithere/argh#93]
I want to be able to do:
````bash
echo 1 | add_one.py
2
````
or
````bash
add_one.py 1
2
````

**Comment by mcameron** [comment]
+1

**Comment by neithere** [comment]
Um...
```python
def main(num=None):
    return int(num or sys.stdin.read()) + 1
```
Usage: `prog -n 1` or `echo 1 | prog

Another option:
```python
def main(num):
    return (num if num != '-' else sys.stdin.read()) + 1
```
Usage: `prog 1` or `echo 1 | prog -`

Yet another option:
```python
@argh.arg('num', nargs='?')
def main(num):
    return int(num or sys.stdin.read()) + 1
```
Usage: `prog 1` or `echo 1 | prog`

Do you think it's enough for your use case?

**Comment by hekaldama** [comment]
Looks like it will. Thanks! I was missing the nargs option.

**Comment by neithere** [comment]
Cool. Leaving the issue open: should include these in the docs.

**Comment by hekaldama** [comment]
I am actually not doing just addition, I am doing either read STDIN or read in a file passed in:
````bash
cat some.yml | script
````
or
````bash
script some.yml
````
and it needs to be able to handle both, and error out still if someone just does:
````bash
script
````
Sorry if this is obvious to more seasoned python programmers.

**Comment by neithere** [comment]
Then your use case is closer to this:
```python
@argh.arg('path', nargs='?')
def main(path):
    f = open(path) if path else sys.stdin
    return f.read()
```

However, I would go with the previously mentioned approach `prog foo.yaml` / `cat foo.yaml | prog -` because it's simple and explicit. Using `-` instead of filename to read from STDIN is a pretty widespread idiom, I believe.

**Comment by hekaldama** [comment]
I think it is widespread as well. Thanks for the comments.
