### ISSUE TITLE
missing git release tag 0.26.1

### ISSUE THREAD

**Issue by anthraxx** [neithere/argh#95]
the git tag for 0.26.1 is missing (last one is 0.26).

It would be awesome if you could make sure to always push a git tag if you release a new version!
I'm moving this library into the repositories of Arch Linux and it is a lot more convenient to watch for releases by just pulling git tags and looking for something new.

thanks for your work

**Comment by kpcyrd** [comment]
Any updates? I'd really like to see that happen :)

**Comment by neithere** [comment]
Sorry, it took a really long time :)
Published next version, added release tag: https://github.com/neithere/argh/releases/tag/v0.26.2
